class ChecklistItem {
  final String id;
  final String tripId;
  final String userId;
  final String itemText;
  final bool isChecked;
  final String category; // documents, packing, bookings, health, money, general
  final bool isAutoGenerated;
  final int sortOrder;
  final DateTime createdAt;

  ChecklistItem({
    required this.id,
    required this.tripId,
    required this.userId,
    required this.itemText,
    this.isChecked = false,
    this.category = 'general',
    this.isAutoGenerated = false,
    this.sortOrder = 0,
    required this.createdAt,
  });

  factory ChecklistItem.fromJson(Map<String, dynamic> json) {
    return ChecklistItem(
      id: json['id'] ?? '',
      tripId: json['trip_id'] ?? '',
      userId: json['user_id'] ?? '',
      itemText: json['item_text'] ?? '',
      isChecked: json['is_checked'] ?? false,
      category: json['category'] ?? 'general',
      isAutoGenerated: json['is_auto_generated'] ?? false,
      sortOrder: json['sort_order'] ?? 0,
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'])
          : DateTime.now(),
    );
  }

  Map<String, dynamic> toInsertJson() => {
        'trip_id': tripId,
        'user_id': userId,
        'item_text': itemText,
        'is_checked': isChecked,
        'category': category,
        'is_auto_generated': isAutoGenerated,
        'sort_order': sortOrder,
      };

  /// Emoji icon per category
  static String categoryIcon(String category) {
    switch (category) {
      case 'documents':
        return '📄';
      case 'packing':
        return '🎒';
      case 'bookings':
        return '🏨';
      case 'health':
        return '💊';
      case 'money':
        return '💳';
      default:
        return '✅';
    }
  }

  static String categoryLabel(String category) {
    switch (category) {
      case 'documents':
        return 'Documents';
      case 'packing':
        return 'Packing';
      case 'bookings':
        return 'Bookings';
      case 'health':
        return 'Health';
      case 'money':
        return 'Money';
      default:
        return 'General';
    }
  }
}
